### ISSUE TITLE
How to use the node_modules tarballs together with npm-local-registry: "npm done. Shutting down proxy"

### ISSUE THREAD

**Issue by johanneskastl** [openSUSE/obs-service-node_modules#40]
Hi,

I found this nice service which comes in handy as I would like to package [headlamp](https://github.com/headlamp-k8s/headlamp) for openSUSE.

However, I am not sure how to use the service properly, or rather why it does not work in [my package](https://build.opensuse.org/package/show/home:ojkastl_buildservice:Branch_devel_kubic/headlamp):

Is this `npm done. Shutting down proxy` to be expected?

```
[   65s] + rm -rf node_modules
[   65s] + rm -f package-lock.json
[   65s] + local-npm-registry /home/abuild/rpmbuild/SOURCES install --with=dev --legacy-peer-deps
[   66s] Serving 96 packages
[   66s] { address: '::1', family: 'IPv6', port: 43873 }
[   66s] request: (ERROR)/npm
[   68s] request: (bad method)/-/npm/v1/security/advisories/bulk
[   68s] request: (bad method)/-/npm/v1/security/audits/quick
[   70s] 
[   70s] added 101 packages in 3s
[   70s] 
[   70s] 20 packages are looking for funding
[   70s]   run `npm fund` for details
[   70s] npm done. Shutting down proxy
[   70s] + RPM_EC=0
[   70s] ++ jobs -p
[   70s] + exit 0
```

**Comment by AdamMajer** [comment]
Yes, this is exactly what should happen. It

 1. reads some packages for npm from directory you specify, so in this case `/home/abuild/rpmbuild/SOURCES`
 2. configures npm to connect to it
 3. runs npm with the parameters you passed to it, so in this case `install --with=dev --legacy-peer-deps`
 4. waits for npm to finish
 5. it shuts down the listening port and removes the npm registry config option setup in step 2

There are also 3 lines logged

  1. request for npm version -- error because it's not there. This is normal version check by npm
  2. (bad method) just mean that these are POST requests to registry to check for security advisories and things like that. Can be ignored.

The other lines are logged by npm itself -- about added packages and looking for funding stuff.

Thanks for the question.

**Comment by johanneskastl** [comment]
Thanks for the explanation.

Hmmm, unfortunately the build is failing in the `npm install` step a little later:

https://build.opensuse.org/package/live_build_log/home:ojkastl_buildservice:Branch_devel_kubic/headlamp/openSUSE_Tumbleweed/x86_64

Is this from transient dependencies not included in the package-lock.json file?

**Comment by AdamMajer** [comment]
On 5/29/24 13:33, Johannes Kastl wrote:
> Is this from transient dependencies not included in the 
> package-lock.json file?

So,

`local-npm-registry %_sourcedir install ...` is another way of running 
`npm install ...`. You don't want to do this again later. It fails later 
because it cannot resolve anything anyway, as expected (no network).

If you need to run `npm install` inside frontend/ , just do that with

   cd frontend; local-npm-registry %_sourcedir install

- Adam

**Comment by johanneskastl** [comment]
Now it fails with a different error, but still because yoctoqueue cannot be found:

```
[    7s] + cd frontend
[    7s] + local-npm-registry /home/abuild/rpmbuild/SOURCES install
[    8s] Serving 96 packages 
[    8s] { address: '::1', family: 'IPv6', port: 45645 }
[   88s] npm ERR! code ECONNREFUSED
[   88s] npm ERR! syscall connect
[   88s] npm ERR! errno ECONNREFUSED                                                                                                                                                                              
[   88s] npm ERR! FetchError: request to http://localhost:45645/yocto-queue/-/yocto-queue-0.1.0.tgz failed, reason: connect ECONNREFUSED 127.0.0.1:45645
[   88s] npm ERR!     at ClientRequest.<anonymous> (/usr/lib64/node_modules/npm21/node_modules/minipass-fetch/lib/index.js:130:14)
[   88s] npm ERR!     at ClientRequest.emit (node:events:519:28)
[   88s] npm ERR!     at _destroy (node:_http_client:880:13)         
[   88s] npm ERR!     at onSocketNT (node:_http_client:900:5)
[   88s] npm ERR!     at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
[   88s] npm ERR!  FetchError: request to http://localhost:45645/yocto-queue/-/yocto-queue-0.1.0.tgz failed, reason: connect ECONNREFUSED 127.0.0.1:45645
[   88s] npm ERR!     at ClientRequest.<anonymous> (/usr/lib64/node_modules/npm21/node_modules/minipass-fetch/lib/index.js:130:14)
[   88s] npm ERR!     at ClientRequest.emit (node:events:519:28)              
[   88s] npm ERR!     at _destroy (node:_http_client:880:13)
[   88s] npm ERR!     at onSocketNT (node:_http_client:900:5)
[   88s] npm ERR!     at process.processTicksAndRejections (node:internal/process/task_queues:83:21) {
[   88s] npm ERR!   code: 'ECONNREFUSED',                                                                
[   88s] npm ERR!   errno: 'ECONNREFUSED',
[   88s] npm ERR!   syscall: 'connect',                                                                  
[   88s] npm ERR!   address: '127.0.0.1',                                                                
[   88s] npm ERR!   port: 45645,                                                                         
[   88s] npm ERR!   type: 'system'                                                                       
[   88s] npm ERR! }
[   88s] npm ERR! 
[   88s] npm ERR! If you are behind a proxy, please make sure that the
[   88s] npm ERR! 'proxy' config is set properly.  See: 'npm help config'
[   88s] 
[   88s] npm ERR! A complete log of this run can be found in: /home/abuild/.npm/_logs/2024-05-29T14_23_40_347Z-debug-0.log
[   88s] An error occurred: NPM returned code: 1
```

I noticed that this is not in the package.json, so it might be unrelated to the service.

**Comment by johanneskastl** [comment]
> I noticed that this is not in the package.json, so it might be unrelated to the service.

I might have picked the wrong package-lock.json for generating the cpio archive. I am currently rebuilding it...

**Comment by johanneskastl** [comment]
OK, now the local registry command fails with a different error:

```
[   27s] Serving 2149 packages
[   27s] { address: '::1', family: 'IPv6', port: 32801 }
[   28s] request: (ERROR)/npm
[   34s] npm ERR! code ETARGET
[   34s] npm ERR! notarget No matching version found for typescript@4.4.3.
[   34s] npm ERR! notarget In most cases you or one of your dependencies are requesting
[   34s] npm ERR! notarget a package version that doesn't exist.
[   34s] 
[   34s] npm ERR! A complete log of this run can be found in: /home/abuild/.npm/_logs/2024-05-29T17_27_29_353Z-debug-0.log
[   34s] An error occurred: NPM returned code: 1
```

It looks like using the `package.json` from the frontend directory was a good idea, but it also seems like the CPIO archive does not contain everything required...

**Comment by johanneskastl** [comment]
There are lots of errors during creation of the CPIO archive:

```
unning source_service 'node_modules' ...
ERROR:color-name: mismatch https://registry.npmjs.org/color-name/-/color-name-1.1.3.tgz <> https://registry.npmjs.org/color-name/-/color-name-1.1.3.tgz, sha512:ef67d27a784cc361d931354778203d2829a91086f35a242c8cdf811dc05b4bdbebd66b6dfaf2633dd92c20135498a016f131540cf24ae52514dd0844f4d1170f <> sha1:a7d0558bd89c42f795dd42328f740831ca53bc25
ERROR:escape-string-regexp: mismatch https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-1.0.5.tgz <> https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-1.0.5.tgz, sha512:bdb468ac1e455105af95ad7a53c47faa06852326b6a86cf00eb366099b982ab6dd494306e88d5908641179f911561b8e9081959deec1437e4349fa35aaf26a16 <> sha1:1b61c0562190a8dff6ae3bb2cf0200ca130b86d4
ERROR:has-flag: mismatch https://registry.npmjs.org/has-flag/-/has-flag-3.0.0.tgz <> https://registry.npmjs.org/has-flag/-/has-flag-3.0.0.tgz, sha512:b0a25fd7e71e401af848c92f427043343b5fe135e95615466ad7aed2df75f1b977d059db1369b8bcd2d7f9559efdda6395bf87ba0198cd6eee4171fdf073c463 <> sha1:b5d454dc2199ae225699f3467e5a07f3b955bafd
ERROR:color-name: mismatch https://registry.npmjs.org/color-name/-/color-name-1.1.3.tgz <> https://registry.npmjs.org/color-name/-/color-name-1.1.3.tgz, sha512:ef67d27a784cc361d931354778203d2829a91086f35a242c8cdf811dc05b4bdbebd66b6dfaf2633dd92c20135498a016f131540cf24ae52514dd0844f4d1170f <> sha1:a7d0558bd89c42f795dd42328f740831ca53bc25
ERROR:escape-string-regexp: mismatch https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-1.0.5.tgz <> https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-1.0.5.tgz, sha512:bdb468ac1e455105af95ad7a53c47faa06852326b6a86cf00eb366099b982ab6dd494306e88d5908641179f911561b8e9081959deec1437e4349fa35aaf26a16 <> sha1:1b61c0562190a8dff6ae3bb2cf0200ca130b86d4
ERROR:has-flag: mismatch https://registry.npmjs.org/has-flag/-/has-flag-3.0.0.tgz <> https://registry.npmjs.org/has-flag/-/has-flag-3.0.0.tgz, sha512:b0a25fd7e71e401af848c92f427043343b5fe135e95615466ad7aed2df75f1b977d059db1369b8bcd2d7f9559efdda6395bf87ba0198cd6eee4171fdf073c463 <> sha1:b5d454dc2199ae225699f3467e5a07f3b955bafd
ERROR:ms: mismatch https://registry.npmjs.org/ms/-/ms-2.0.0.tgz <> https://registry.npmjs.org/ms/-/ms-2.0.0.tgz, sha512:4e9a7ad0fe885090d3b8eabfe59f1c76c93326e8dfc2a7ce4e4af02308fb211212a679099d3e92c89e0f08f9c63281630bd75d85a979295218b40b7dee2c74e4 <> sha1:5608aeadfc00be6c2901df5f9861788de0d597c8
ERROR:ms: mismatch https://registry.npmjs.org/ms/-/ms-2.0.0.tgz <> https://registry.npmjs.org/ms/-/ms-2.0.0.tgz, sha512:4e9a7ad0fe885090d3b8eabfe59f1c76c93326e8dfc2a7ce4e4af02308fb211212a679099d3e92c89e0f08f9c63281630bd75d85a979295218b40b7dee2c74e4 <> sha1:5608aeadfc00be6c2901df5f9861788de0d597c8
ERROR:isarray: mismatch https://registry.npmjs.org/isarray/-/isarray-1.0.0.tgz <> https://registry.npmjs.org/isarray/-/isarray-1.0.0.tgz, sha512:54b82121634ce842d0ce8ef3c26720d0d99357258a623bc878cf37ca3a74c110d39949eb33aefc7d06dc281a3a9f6089105d2cce81bfff2b60f932a56bcf402d <> sha1:bb935d48582cba168c06834957a54a3e07124f11
ERROR:ms: mismatch https://registry.npmjs.org/ms/-/ms-2.0.0.tgz <> https://registry.npmjs.org/ms/-/ms-2.0.0.tgz, sha512:4e9a7ad0fe885090d3b8eabfe59f1c76c93326e8dfc2a7ce4e4af02308fb211212a679099d3e92c89e0f08f9c63281630bd75d85a979295218b40b7dee2c74e4 <> sha1:5608aeadfc00be6c2901df5f9861788de0d597c8
ERROR:ms: mismatch https://registry.npmjs.org/ms/-/ms-2.0.0.tgz <> https://registry.npmjs.org/ms/-/ms-2.0.0.tgz, sha512:4e9a7ad0fe885090d3b8eabfe59f1c76c93326e8dfc2a7ce4e4af02308fb211212a679099d3e92c89e0f08f9c63281630bd75d85a979295218b40b7dee2c74e4 <> sha1:5608aeadfc00be6c2901df5f9861788de0d597c8
ERROR:ms: mismatch https://registry.npmjs.org/ms/-/ms-2.0.0.tgz <> https://registry.npmjs.org/ms/-/ms-2.0.0.tgz, sha512:4e9a7ad0fe885090d3b8eabfe59f1c76c93326e8dfc2a7ce4e4af02308fb211212a679099d3e92c89e0f08f9c63281630bd75d85a979295218b40b7dee2c74e4 <> sha1:5608aeadfc00be6c2901df5f9861788de0d597c8
ERROR:isarray: mismatch https://registry.npmjs.org/isarray/-/isarray-1.0.0.tgz <> https://registry.npmjs.org/isarray/-/isarray-1.0.0.tgz, sha512:54b82121634ce842d0ce8ef3c26720d0d99357258a623bc878cf37ca3a74c110d39949eb33aefc7d06dc281a3a9f6089105d2cce81bfff2b60f932a56bcf402d <> sha1:bb935d48582cba168c06834957a54a3e07124f11
ERROR:ms: mismatch https://registry.npmjs.org/ms/-/ms-2.0.0.tgz <> https://registry.npmjs.org/ms/-/ms-2.0.0.tgz, sha512:4e9a7ad0fe885090d3b8eabfe59f1c76c93326e8dfc2a7ce4e4af02308fb211212a679099d3e92c89e0f08f9c63281630bd75d85a979295218b40b7dee2c74e4 <> sha1:5608aeadfc00be6c2901df5f9861788de0d597c8
ERROR:isarray: mismatch https://registry.npmjs.org/isarray/-/isarray-1.0.0.tgz <> https://registry.npmjs.org/isarray/-/isarray-1.0.0.tgz, sha512:54b82121634ce842d0ce8ef3c26720d0d99357258a623bc878cf37ca3a74c110d39949eb33aefc7d06dc281a3a9f6089105d2cce81bfff2b60f932a56bcf402d <> sha1:bb935d48582cba168c06834957a54a3e07124f11
ERROR:color-name: mismatch https://registry.npmjs.org/color-name/-/color-name-1.1.3.tgz <> https://registry.npmjs.org/color-name/-/color-name-1.1.3.tgz, sha512:ef67d27a784cc361d931354778203d2829a91086f35a242c8cdf811dc05b4bdbebd66b6dfaf2633dd92c20135498a016f131540cf24ae52514dd0844f4d1170f <> sha1:a7d0558bd89c42f795dd42328f740831ca53bc25
ERROR:escape-string-regexp: mismatch https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-1.0.5.tgz <> https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-1.0.5.tgz, sha512:bdb468ac1e455105af95ad7a53c47faa06852326b6a86cf00eb366099b982ab6dd494306e88d5908641179f911561b8e9081959deec1437e4349fa35aaf26a16 <> sha1:1b61c0562190a8dff6ae3bb2cf0200ca130b86d4
ERROR:has-flag: mismatch https://registry.npmjs.org/has-flag/-/has-flag-3.0.0.tgz <> https://registry.npmjs.org/has-flag/-/has-flag-3.0.0.tgz, sha512:b0a25fd7e71e401af848c92f427043343b5fe135e95615466ad7aed2df75f1b977d059db1369b8bcd2d7f9559efdda6395bf87ba0198cd6eee4171fdf073c463 <> sha1:b5d454dc2199ae225699f3467e5a07f3b955bafd
ERROR:ms: mismatch https://registry.npmjs.org/ms/-/ms-2.0.0.tgz <> https://registry.npmjs.org/ms/-/ms-2.0.0.tgz, sha512:4e9a7ad0fe885090d3b8eabfe59f1c76c93326e8dfc2a7ce4e4af02308fb211212a679099d3e92c89e0f08f9c63281630bd75d85a979295218b40b7dee2c74e4 <> sha1:5608aeadfc00be6c2901df5f9861788de0d597c8
ERROR:ms: mismatch https://registry.npmjs.org/ms/-/ms-2.0.0.tgz <> https://registry.npmjs.org/ms/-/ms-2.0.0.tgz, sha512:4e9a7ad0fe885090d3b8eabfe59f1c76c93326e8dfc2a7ce4e4af02308fb211212a679099d3e92c89e0f08f9c63281630bd75d85a979295218b40b7dee2c74e4 <> sha1:5608aeadfc00be6c2901df5f9861788de0d597c8
ERROR:color-name: mismatch https://registry.npmjs.org/color-name/-/color-name-1.1.3.tgz <> https://registry.npmjs.org/color-name/-/color-name-1.1.3.tgz, sha512:ef67d27a784cc361d931354778203d2829a91086f35a242c8cdf811dc05b4bdbebd66b6dfaf2633dd92c20135498a016f131540cf24ae52514dd0844f4d1170f <> sha1:a7d0558bd89c42f795dd42328f740831ca53bc25
ERROR:escape-string-regexp: mismatch https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-1.0.5.tgz <> https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-1.0.5.tgz, sha512:bdb468ac1e455105af95ad7a53c47faa06852326b6a86cf00eb366099b982ab6dd494306e88d5908641179f911561b8e9081959deec1437e4349fa35aaf26a16 <> sha1:1b61c0562190a8dff6ae3bb2cf0200ca130b86d4
ERROR:has-flag: mismatch https://registry.npmjs.org/has-flag/-/has-flag-3.0.0.tgz <> https://registry.npmjs.org/has-flag/-/has-flag-3.0.0.tgz, sha512:b0a25fd7e71e401af848c92f427043343b5fe135e95615466ad7aed2df75f1b977d059db1369b8bcd2d7f9559efdda6395bf87ba0198cd6eee4171fdf073c463 <> sha1:b5d454dc2199ae225699f3467e5a07f3b955bafd
ERROR:tr46: mismatch https://registry.npmjs.org/tr46/-/tr46-1.0.1.tgz <> https://registry.npmjs.org/tr46/-/tr46-1.0.1.tgz, sha512:753a68c048dc950eca831e5274192a473561111417a2ff3f97d16df5d54cf5f9a0d16d0a41255a5d7f53e22eadc023cdb58899339de5a5249403025b14f387c4 <> sha1:a8b13fd6bfd2489519674ccde55ba3693b706d09
```

Is this a npmjs registry issue? Would it be better to use a different one?

**Comment by AdamMajer** [comment]
On 5/29/24 21:54, Johannes Kastl wrote:
> It looks like using the |package.json| from the frontend directory was a 
> good idea, but it also seems like the CPIO archive does not contain 
> everything required...

You need to create the package-lock.json from the package.json.

cd frontend; npm i --package-lock-only

then use this package-lock.json. It should have typescript in it. You 
can check this.

- Adam

**Comment by johanneskastl** [comment]
Thanks for your help, Adam! Using the package-lock.json from the right branch seems to have worked.

Now I have the next issue: headlamp uses two directories, `frontend` and `app`. I got frontend to build properly (hopefully), but of course now I need to do the same with the `app` folder.

Can I use the service twice? I could set different names and offsets in `_service`, but I cannot specify a different package-lock.json, right? Or is there a way to do that?

**Comment by AdamMajer** [comment]
On 6/2/24 09:38, Johannes Kastl wrote> Can I use the service twice? I 
could set different names and offsets in
> |_service|, but I cannot specify a different package-lock.json, right? 
> Or is there a way to do that?

There is a way to do it :-)

https://github.com/openSUSE/obs-service-node_modules/commit/01453ac8419ee89c05f2bddd05e6c55f44e9d5fd

Basically, this is not well documented, but you can combine the two 
package-lock.json files into one with something like,

{
   "frontend.json": <cat frontend's package-lock.json>,
   "app.json": <cat app's package-lock.json>
}

then use this as the input for node_modules service and you should get 
NPM modules for both of the npm modules.

There should be a better way of handing this, but it's at the "patches 
welcome" phase.

- Adam

**Comment by johanneskastl** [comment]
I finally found some time to dig into this, and while I tried to implement handing over the name of the lock file as an argument I found that this already exists:

https://github.com/openSUSE/obs-service-node_modules/blob/master/node_modules.py#L564

```
    parser.add_argument(
        "-i",
        "--input",
        metavar="FILE",
        default="package-lock.json",
        help="input package lock file",
    )
```

So, now I am using this in my service, and at least it starts fetching the node modules:

```
  <service name="node_modules" mode="manual">
    <param name="input">frontend_package-lock.json</param>
    <param name="cpio">frontend_node_modules.obscpio</param>
    <param name="output">frontend_node_modules.spec.inc</param>
    <param name="source-offset">10000</param>
  </service>
  <service name="node_modules" mode="manual">
    <param name="input">app_package-lock.json</param>     
    <param name="cpio">app_node_modules.obscpio</param>     
    <param name="output">app_node_modules.spec.inc</param>     
    <param name="source-offset">20000</param>
  </service>
```

Let's see if it compiles...

P.S.: This option is missing in the `service` file, I'll create a PR to add it.
https://github.com/openSUSE/obs-service-node_modules/blob/master/node_modules.service
