### ISSUE TITLE
Unexpected module key: make

### ISSUE THREAD

**Issue by bnavigator** [openSUSE/obs-service-node_modules#43]
Trying to use this for bokeh:

```
Running source_service 'node_modules' ...
Traceback (most recent call last):
  File "/usr/lib/obs/service/node_modules", line 630, in <module>
    sys.exit(main(args))
             ^^^^^^^^^^
  File "/usr/lib/obs/service/node_modules", line 382, in main
    process_packagelock_file(js)
  File "/usr/lib/obs/service/node_modules", line 347, in process_packagelock_file
    collect_v3_deps(js["packages"])
  File "/usr/lib/obs/service/node_modules", line 318, in collect_v3_deps
    raise Exception("unexpected module key: " + module)
Exception: unexpected module key: make
Aborting: service call failed:  /usr/lib/obs/service/node_modules --cpio node_modules.obscpio --output node_modules.spec.inc --source-offset 10000 --outdir /home/ben/src/osc/devel:languages:python:numeric/python-bokeh/tmp6sfw2iag.node_modules.service
```

As per the instructions, the package-lock.json is created by running `npm install --package-lock-only --legacy-peer-deps --ignore-scripts` inside [bokehjs](https://github.com/bokeh/bokeh/tree/3.6.1/bokehjs)

:memo:  [package-lock.json](https://github.com/user-attachments/files/17937419/package-lock.json)

**Comment by AdamMajer** [comment]
This package is using workspaces. I wonder if this somehow has something to do here. I'll look into this

**Comment by AdamMajer** [comment]
Workspaces should be fixed in 0f00d148288be9498ac9eeae3cc3dc6fe1bc8d50
